'use strict';

const ref = require('../src/shared/miner/reference');
const { keyedHash } = require('../src/shared/miner/blake3');
const { JACKPOT_BUCKETS, meetsTarget } = require('../src/shared/miner/pearlhash');

// Known-answer vectors for the Pearl PoW, generated by the JS reference and
// frozen here.
//
// WHAT THESE ARE FOR: the CUDA core must reproduce every one of these exactly.
// The failure they exist to catch is the one with no error message — a GPU core
// with a subtly wrong hash, fold or endianness runs at full speed, reports a
// healthy hashrate, and simply never earns anything. Freezing the intermediates
// (not just the final hash) means a mismatch localises to a stage instead of
// just "wrong".
//
// WHAT THEY ARE NOT: proof of agreement with the Pearl network. They pin OUR
// semantics so the JS and CUDA sides provably agree and no future edit to either
// drifts silently. Network agreement needs a share accepted by a real pool.

// A deliberately tiny profile — the mainnet one is 131072×131072×4096 and would
// take days in JS. The structure exercised is identical: multiple rank chunks,
// a multi-row/multi-column tile, and the lane rotation.
const { PROFILE } = require('../src/shared/miner/pearlhash');

// Small in m/n/k so the oracle runs in milliseconds, but STRUCTURALLY the real
// thing: k/rank = 16 chunks (one per lane) and the protocol's own 4x8 tile index
// sets. Mainnet's k = 2048 would need ~1M keyed hashes per run.
const TINY = {
  k: 256, rank: 16, mmaType: 0,
  rows: PROFILE.rows, cols: PROFILE.cols,
  m: 128, n: 128,
};

function header76() {
  const h = Buffer.alloc(76);
  for (let i = 0; i < 76; i++) h[i] = i;
  return h;
}
function operandA() {
  const a = new Int8Array(128 * 256);
  for (let i = 0; i < a.length; i++) a[i] = ((i * 7) % 127) - 63;
  return a;
}
function operandB() {
  const b = new Int8Array(128 * 256);
  for (let i = 0; i < b.length; i++) b[i] = ((i * 13) % 127) - 63;
  return b;
}

const VECTOR = {
  jobKey: 'ed86c1bcb417ade4432242275f69221fbff1dd07d9f5addea98f826e775d6fa7',
  hashA: 'f674a74e80fdecbc9eaff33ddab203a39de062d4227e0f148b6774797be40e9e',
  hashB: '31aa2952017fb3fc4caa8cfebcb3652179679da1d3c1f69cd874e8d3cc048134',
  bSeed: '970baa7e866a33d46e8984339c2e0c69eb9c3e68303b033ec7210a8f418156f7',
  aSeed: '0d64adb205e8fde1f1254331825206782f3b49d5c91153994ddb148fbbf93bbd',
  jackpotHash: '0ebcdd46242eb60e9a774a097df380b1edc5ed9ee154572b4e6973fb2a4520b9',
};

describe('PearlHash reference — known-answer vector', () => {
  const out = ref.computePow({ header: header76(), profile: TINY, A: operandA(), Bt: operandB() });

  test('job_key = blake3(header ‖ config52)', () => {
    expect(out.jobKey.toString('hex')).toBe(VECTOR.jobKey);
  });

  test('the operand commitments match', () => {
    expect(out.hashA.toString('hex')).toBe(VECTOR.hashA);
    expect(out.hashB.toString('hex')).toBe(VECTOR.hashB);
  });

  // b_seed is derived FIRST and then feeds a_seed. The derivation is not
  // symmetric, so swapping them yields a different transcript with no error.
  test('the seeds match, in the order the spec derives them', () => {
    expect(out.bSeed.toString('hex')).toBe(VECTOR.bSeed);
    expect(out.aSeed.toString('hex')).toBe(VECTOR.aSeed);
    expect(out.aSeed).not.toEqual(out.bSeed);
  });

  // k/rank = 16 chunks against 16 lanes, so every lane is written exactly once
  // and the rotation never wraps. The earlier k = 4096 folded each lane twice
  // and left the tail zeroed.
  test('every transcript lane is populated exactly once', () => {
    expect(out.jackpot).toHaveLength(JACKPOT_BUCKETS);
    expect(out.jackpot.filter((x) => x !== 0)).toHaveLength(JACKPOT_BUCKETS);
  });

  test('the final jackpot hash matches', () => {
    expect(out.jackpotHash.toString('hex')).toBe(VECTOR.jackpotHash);
  });

  test('the transcript is 64 bytes, little-endian per lane', () => {
    expect(out.transcript).toHaveLength(64);
    // The lanes themselves are checked above; here the concern is only that the
    // 64-byte view is a little-endian rendering of them.
    expect(out.transcript.readUInt32LE(0)).toBe(out.jackpot[0]);
    expect(out.transcript.readUInt32LE(4)).toBe(out.jackpot[1]);
  });

  test('the final hash is keyed under a_seed, not b_seed', () => {
    expect(out.jackpotHash).toEqual(keyedHash(out.aSeed, out.transcript));
    expect(out.jackpotHash).not.toEqual(keyedHash(out.bSeed, out.transcript));
  });

  test('it is deterministic', () => {
    const again = ref.computePow({ header: header76(), profile: TINY, A: operandA(), Bt: operandB() });
    expect(again.jackpotHash).toEqual(out.jackpotHash);
  });
});

describe('PearlHash reference — sensitivity', () => {
  const base = ref.computePow({ header: header76(), profile: TINY, A: operandA(), Bt: operandB() });

  // Every input must matter. A stage that silently ignores one of these is the
  // classic way a miner produces plausible-looking work that never validates.
  test('a one-bit header change changes the result', () => {
    const h = header76();
    h[40] ^= 1;
    const out = ref.computePow({ header: h, profile: TINY, A: operandA(), Bt: operandB() });
    expect(out.jobKey).not.toEqual(base.jobKey);
    expect(out.jackpotHash).not.toEqual(base.jackpotHash);
  });

  test('a one-element operand change changes the result', () => {
    const A = operandA();
    A[5] ^= 1;
    const out = ref.computePow({ header: header76(), profile: TINY, A, Bt: operandB() });
    expect(out.hashA).not.toEqual(base.hashA);
    expect(out.jackpotHash).not.toEqual(base.jackpotHash);
  });

  test('the profile is bound into the result through config52', () => {
    const out2 = ref.computePow({
      header: header76(), profile: { ...TINY, rank: 32 }, A: operandA(), Bt: operandB(),
    });
    expect(out2.jobKey).not.toEqual(base.jobKey);
  });

  // m and n are the miner's own dimensions and are NOT hashed, so changing them
  // must leave job_key alone even though it changes what gets mined.
  test('m and n do not enter job_key', () => {
    const out2 = ref.computePow({
      header: header76(), profile: { ...TINY, m: 256, n: 256 }, A: operandA(), Bt: operandB(),
    });
    expect(out2.jobKey).toEqual(base.jobKey);
  });
});

describe('PearlHash reference — pieces', () => {
  test('pad1024 rounds up to whole chunks and never returns empty', () => {
    expect(ref.pad1024(Buffer.alloc(0))).toHaveLength(1024);
    expect(ref.pad1024(Buffer.alloc(1))).toHaveLength(1024);
    expect(ref.pad1024(Buffer.alloc(1024))).toHaveLength(1024);
    expect(ref.pad1024(Buffer.alloc(1025))).toHaveLength(2048);
    // Padding must be zeros, and must preserve the payload.
    const p = ref.pad1024(Buffer.from([1, 2, 3]));
    expect(p.slice(0, 3)).toEqual(Buffer.from([1, 2, 3]));
    expect(p.slice(3).every((b) => b === 0)).toBe(true);
  });

  // The int7 range keeps products inside int32 without saturating, which is why
  // the reference uses Int7xInt7ToInt32 rather than full int8.
  test('noise draws land in the int7 range and vary with the index', () => {
    const seed = Buffer.alloc(32, 7);
    const seen = new Set();
    for (let i = 0; i < 200; i++) {
      const v = ref.noiseDraw(seed, i);
      expect(v).toBeGreaterThanOrEqual(-63);
      expect(v).toBeLessThanOrEqual(63);
      seen.add(v);
    }
    expect(seen.size).toBeGreaterThan(20); // not a constant
  });

  test('noise draws depend on the seed', () => {
    const a = ref.noiseDraw(Buffer.alloc(32, 1), 0);
    const b = ref.noiseDraw(Buffer.alloc(32, 2), 0);
    // Overwhelmingly likely to differ; if they ever collide the next index will not.
    expect([a, ref.noiseDraw(Buffer.alloc(32, 1), 1)])
      .not.toEqual([b, ref.noiseDraw(Buffer.alloc(32, 2), 1)]);
  });

  test('noiseFactor fills rows × rank', () => {
    expect(ref.noiseFactor(Buffer.alloc(32, 3), 4, 5, 0)).toHaveLength(20);
  });

  test('rotl13 matches the fold definition', () => {
    expect(ref.rotl13(1)).toBe(1 << 13);
    expect(ref.rotl13(0)).toBe(0);
    expect(ref.rotl13(0xffffffff)).toBe(0xffffffff >>> 0);
  });

  test('transcriptBytes is a 64-byte little-endian view of the lanes', () => {
    const j = new Uint32Array(JACKPOT_BUCKETS);
    j[0] = 0x01020304;
    const b = ref.transcriptBytes(j);
    expect(b).toHaveLength(64);
    expect(b[0]).toBe(0x04);
    expect(b[3]).toBe(0x01);
  });

  test('jobKey and deriveSeeds are usable on their own', () => {
    const key = ref.jobKey(header76(), TINY);
    expect(key).toHaveLength(32);
    const s = ref.deriveSeeds(key, operandA(), operandB());
    expect(s.aSeed).toHaveLength(32);
    expect(s.bSeed).toHaveLength(32);
  });
});

describe('PearlHash reference — target comparison', () => {
  // The comparison the whole thing exists to feed. The reference value is read
  // little-endian; the pool's target is big-endian. Opposite, and load-bearing.
  test('the computed value is comparable against a target', () => {
    const out = ref.computePow({ header: header76(), profile: TINY, A: operandA(), Bt: operandB() });
    expect(typeof out.value).toBe('bigint');
    // An all-ones target accepts anything; a zero target accepts nothing.
    expect(meetsTarget(out.jackpotHash, (1n << 256n) - 1n)).toBe(true);
    expect(meetsTarget(out.jackpotHash, 0n)).toBe(false);
    expect(out.value).toBeGreaterThan(0n);
  });
});
