'use strict';

const ref = require('../src/shared/miner/reference');
const { keyedHash } = require('../src/shared/miner/blake3');
const { JACKPOT_BUCKETS, meetsTarget } = require('../src/shared/miner/pearlhash');

// Known-answer vectors for the Pearl PoW, generated by the JS reference and
// frozen here.
//
// WHAT THESE ARE FOR: the CUDA core must reproduce every one of these exactly.
// The failure they exist to catch is the one with no error message — a GPU core
// with a subtly wrong hash, fold or endianness runs at full speed, reports a
// healthy hashrate, and simply never earns anything. Freezing the intermediates
// (not just the final hash) means a mismatch localises to a stage instead of
// just "wrong".
//
// WHAT THEY ARE NOT: proof of agreement with the Pearl network. They pin OUR
// semantics so the JS and CUDA sides provably agree and no future edit to either
// drifts silently. Network agreement needs a share accepted by a real pool.

// A deliberately tiny profile — the mainnet one is 131072×131072×4096 and would
// take days in JS. The structure exercised is identical: multiple rank chunks,
// a multi-row/multi-column tile, and the lane rotation.
const { PROFILE } = require('../src/shared/miner/pearlhash');

// Small in m/n/k so the oracle runs in milliseconds, but STRUCTURALLY the real
// thing: k/rank = 16 chunks (one per lane) and the protocol's own 4x8 tile index
// sets. Mainnet's k = 2048 would need ~1M keyed hashes per run.
//
// rank is 32, not 16. The reference asserts that rank is a power of two AND a
// multiple of BLAKE3_DIGEST_SIZE, because the dense factor is generated one
// 32-byte digest at a time. A rank of 16 is not a geometry the protocol admits,
// and on the device it makes the per-row digest count round to zero.
const TINY = {
  k: 512, rank: 32, mmaType: 0,
  rows: PROFILE.rows, cols: PROFILE.cols,
  m: 128, n: 128,
};

function header76() {
  const h = Buffer.alloc(76);
  for (let i = 0; i < 76; i++) h[i] = i;
  return h;
}
// int7 operands. The range matters: the noise adds another int7, and the sum has
// to stay inside int8 for the Int7xInt7ToInt32 MMA.
function operandA() {
  const a = new Int8Array(128 * 512);
  for (let i = 0; i < a.length; i++) a[i] = ((i * 7) % 127) - 63;
  return a;
}
function operandB() {
  const b = new Int8Array(128 * 512);
  for (let i = 0; i < b.length; i++) b[i] = ((i * 13) % 127) - 63;
  return b;
}

const VECTOR = {
  jobKey: '6067f255c955f1cf849b2fc5107f4c769b94a705b59e6b792eb689a791038a78',
  hashA: '9d3b42c623c95c41b7e1d0a634674f7e440a5424f2eb3f8b326e96ca06b6cdc2',
  hashB: 'b6b10c4b8c8173c2a05f2f5a6a8a2d6c34dd42889f4c248fd0446f8580c907af',
  bSeed: 'fc11a3328fe77830e289334a057e0c9857cd752e10c156a6544a501752c9949a',
  aSeed: '53de1c85b1a1b09a40c72eba188edf85865007d251f8db80de17471db73e7687',
  jackpotHash: 'f6b96ebcb7c3cf11000d9386143d60c155c470d8c53688cee8d6a428ff33fae6',
};

describe('PearlHash reference — known-answer vector', () => {
  const out = ref.computePow({ header: header76(), profile: TINY, A: operandA(), Bt: operandB() });

  test('job_key = blake3(header ‖ config52)', () => {
    expect(out.jobKey.toString('hex')).toBe(VECTOR.jobKey);
  });

  test('the operand commitments match', () => {
    expect(out.hashA.toString('hex')).toBe(VECTOR.hashA);
    expect(out.hashB.toString('hex')).toBe(VECTOR.hashB);
  });

  // b_seed is derived FIRST and then feeds a_seed. The derivation is not
  // symmetric, so swapping them yields a different transcript with no error.
  test('the seeds match, in the order the spec derives them', () => {
    expect(out.bSeed.toString('hex')).toBe(VECTOR.bSeed);
    expect(out.aSeed.toString('hex')).toBe(VECTOR.aSeed);
    expect(out.aSeed).not.toEqual(out.bSeed);
  });

  // k/rank = 16 chunks against 16 lanes, so every lane is written exactly once
  // and the rotation never wraps. The earlier k = 4096 folded each lane twice
  // and left the tail zeroed.
  test('every transcript lane is populated exactly once', () => {
    expect(out.jackpot).toHaveLength(JACKPOT_BUCKETS);
    expect(out.jackpot.filter((x) => x !== 0)).toHaveLength(JACKPOT_BUCKETS);
  });

  test('the final jackpot hash matches', () => {
    expect(out.jackpotHash.toString('hex')).toBe(VECTOR.jackpotHash);
  });

  test('the transcript is 64 bytes, little-endian per lane', () => {
    expect(out.transcript).toHaveLength(64);
    // The lanes themselves are checked above; here the concern is only that the
    // 64-byte view is a little-endian rendering of them.
    expect(out.transcript.readUInt32LE(0)).toBe(out.jackpot[0]);
    expect(out.transcript.readUInt32LE(4)).toBe(out.jackpot[1]);
  });

  test('the final hash is keyed under a_seed, not b_seed', () => {
    expect(out.jackpotHash).toEqual(keyedHash(out.aSeed, out.transcript));
    expect(out.jackpotHash).not.toEqual(keyedHash(out.bSeed, out.transcript));
  });

  test('it is deterministic', () => {
    const again = ref.computePow({ header: header76(), profile: TINY, A: operandA(), Bt: operandB() });
    expect(again.jackpotHash).toEqual(out.jackpotHash);
  });
});

describe('PearlHash reference — sensitivity', () => {
  const base = ref.computePow({ header: header76(), profile: TINY, A: operandA(), Bt: operandB() });

  // Every input must matter. A stage that silently ignores one of these is the
  // classic way a miner produces plausible-looking work that never validates.
  test('a one-bit header change changes the result', () => {
    const h = header76();
    h[40] ^= 1;
    const out = ref.computePow({ header: h, profile: TINY, A: operandA(), Bt: operandB() });
    expect(out.jobKey).not.toEqual(base.jobKey);
    expect(out.jackpotHash).not.toEqual(base.jackpotHash);
  });

  test('a one-element operand change changes the result', () => {
    const A = operandA();
    A[5] ^= 1;
    const out = ref.computePow({ header: header76(), profile: TINY, A, Bt: operandB() });
    expect(out.hashA).not.toEqual(base.hashA);
    expect(out.jackpotHash).not.toEqual(base.jackpotHash);
  });

  test('the profile is bound into the result through config52', () => {
    const out2 = ref.computePow({
      header: header76(), profile: { ...TINY, rank: 64 }, A: operandA(), Bt: operandB(),
    });
    expect(out2.jobKey).not.toEqual(base.jobKey);
  });

  // m and n are the miner's own dimensions and are NOT hashed, so changing them
  // must leave job_key alone even though it changes what gets mined.
  test('m and n do not enter job_key', () => {
    const out2 = ref.computePow({
      header: header76(), profile: { ...TINY, m: 256, n: 256 }, A: operandA(), Bt: operandB(),
    });
    expect(out2.jobKey).toEqual(base.jobKey);
  });
});

describe('PearlHash reference — pieces', () => {
  test('pad1024 rounds up to whole chunks and never returns empty', () => {
    expect(ref.pad1024(Buffer.alloc(0))).toHaveLength(1024);
    expect(ref.pad1024(Buffer.alloc(1))).toHaveLength(1024);
    expect(ref.pad1024(Buffer.alloc(1024))).toHaveLength(1024);
    expect(ref.pad1024(Buffer.alloc(1025))).toHaveLength(2048);
    // Padding must be zeros, and must preserve the payload.
    const p = ref.pad1024(Buffer.from([1, 2, 3]));
    expect(p.slice(0, 3)).toEqual(Buffer.from([1, 2, 3]));
    expect(p.slice(3).every((b) => b === 0)).toBe(true);
  });

  test('rotl13 matches the fold definition', () => {
    expect(ref.rotl13(1)).toBe(1 << 13);
    expect(ref.rotl13(0)).toBe(0);
    expect(ref.rotl13(0xffffffff)).toBe(0xffffffff >>> 0);
  });

  test('transcriptBytes is a 64-byte little-endian view of the lanes', () => {
    const j = new Uint32Array(JACKPOT_BUCKETS);
    j[0] = 0x01020304;
    const b = ref.transcriptBytes(j);
    expect(b).toHaveLength(64);
    expect(b[0]).toBe(0x04);
    expect(b[3]).toBe(0x01);
  });

  test('jobKey and deriveSeeds are usable on their own', () => {
    const key = ref.jobKey(header76(), TINY);
    expect(key).toHaveLength(32);
    const s = ref.deriveSeeds(key, operandA(), operandB());
    expect(s.aSeed).toHaveLength(32);
    expect(s.bSeed).toHaveLength(32);
  });
});

describe('PearlHash reference — target comparison', () => {
  // The comparison the whole thing exists to feed. The reference value is read
  // little-endian; the pool's target is big-endian. Opposite, and load-bearing.
  test('the computed value is comparable against a target', () => {
    const out = ref.computePow({ header: header76(), profile: TINY, A: operandA(), Bt: operandB() });
    expect(typeof out.value).toBe('bigint');
    // An all-ones target accepts anything; a zero target accepts nothing.
    expect(meetsTarget(out.jackpotHash, (1n << 256n) - 1n)).toBe(true);
    expect(meetsTarget(out.jackpotHash, 0n)).toBe(false);
    expect(out.value).toBeGreaterThan(0n);
  });
});
